import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
const tierMeta = { Bronze: { emoji: '🌰', className: 'tier-bronze' }, Silver: { emoji: '🥈', className: 'tier-silver' }, Gold: { emoji: '🏆', className: 'tier-gold' }, Platinum: { emoji: '💎', className: 'tier-platinum' } };

export default function AdminDashboard({ token }) {
  const [members, setMembers] = useState([]); const [events, setEvents] = useState([]); const [sort, setSort] = useState('createdAt'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const pageSize = 8;
  useEffect(() => { const load = async () => { try { const config = { headers: { Authorization: `Bearer ${token}` } }; const [membersResponse, outboxResponse] = await Promise.all([axios.get(`${API_URL}/api/members?limit=1000`, config), axios.get(`${API_URL}/outbox`, config)]); setMembers(membersResponse.data.members || []); setEvents(outboxResponse.data.events || []); } catch (requestError) { setError(requestError.response?.data?.error || 'Unable to load analytics'); } finally { setLoading(false); } }; if (token) load(); }, [token]);
  const sortedMembers = useMemo(() => [...members].sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : sort === 'points' ? b.totalPointsEarned - a.totalPointsEarned : new Date(b.createdAt) - new Date(a.createdAt)), [members, sort]);
  const visibleMembers = sortedMembers.slice((page - 1) * pageSize, page * pageSize); const totalPoints = members.reduce((sum, member) => sum + (member.totalPointsEarned || 0), 0); const tiers = Object.keys(tierMeta).map((tier) => ({ tier, count: members.filter((member) => member.tier === tier).length }));
  return <main className="page-shell admin-page"><div className="page-intro"><div><p className="eyebrow">☕ ROASTERY CONTROL ROOM</p><h1>Good morning, curator.</h1><p>One calm view of your café community, their momentum, and the moments that matter.</p></div><button className="gradient-button" onClick={() => window.location.reload()}>↻ Refresh analytics</button></div>{error && <div className="alert error-message">⚠️ {error}</div>}{loading ? <Loader /> : <><section className="analytics-grid"><StatCard icon="👥" label="Total members" value={members.length} tone="orange" detail="across your café" /><StatCard icon="✨" label="Points distributed" value={totalPoints.toLocaleString()} tone="green" detail="lifetime earned" /><StatCard icon="💰" label="Total earned" value={members.reduce((sum, member) => sum + (member.totalMoneySpent || 0), 0).toLocaleString()} tone="purple" detail="₹ tracked" /><StatCard icon="🔔" label="Pending notifications" value={events.filter((event) => !event.deliveredAt).length} tone="pink" detail="in the outbox" /></section><section className="tier-grid">{tiers.map(({ tier, count }) => <article className={`tier-stat ${tierMeta[tier].className}`} key={tier}><span className="tier-emoji">{tierMeta[tier].emoji}</span><div><strong>{count}</strong><span>{tier} members</span></div><small>{members.length ? Math.round(count / members.length * 100) : 0}% of community</small></article>)}</section><section className="panel-card table-panel"><div className="panel-heading"><div><p className="eyebrow">THE COMMUNITY LEDGER</p><h2>Members at a glance</h2></div><label className="select-wrap">Sort <select value={sort} onChange={(event) => { setSort(event.target.value); setPage(1); }}><option value="createdAt">Newest first</option><option value="name">Name A–Z</option><option value="points">Most points</option></select></label></div><div className="table-scroll"><table className="modern-table"><thead><tr><th>Member</th><th>Phone</th><th>Tier</th><th>Balance</th><th>Lifetime earned</th></tr></thead><tbody>{visibleMembers.map((member) => <tr key={member._id}><td><span className="table-person"><span className="avatar">{initials(member.name)}</span><span><strong>{member.name}</strong><small>{member.email}</small></span></span></td><td>{member.phoneNumber}</td><td><span className={`tier-badge ${tierMeta[member.tier]?.className || 'tier-bronze'}`}>{tierMeta[member.tier]?.emoji} {member.tier}</span></td><td><strong>{member.pointsBalance?.toLocaleString() || 0}</strong> pts</td><td>{member.totalPointsEarned?.toLocaleString() || 0} pts</td></tr>)}</tbody></table></div><div className="pagination-row"><span>Showing {visibleMembers.length} of {members.length} members</span><div><button disabled={page === 1} onClick={() => setPage(page - 1)}>←</button><strong>{page}</strong><button disabled={page >= Math.ceil(sortedMembers.length / pageSize)} onClick={() => setPage(page + 1)}>→</button></div></div></section></>}</main>;
}

function StatCard({ icon, label, value, detail, tone }) { return <article className={`analytics-card tone-${tone}`}><span className="stat-icon">{icon}</span><p>{label}</p><strong>{value}</strong><small>{detail} <i>↗</i></small></article>; }
function Loader() { return <div className="loading-state"><span className="spinner" /> Gathering your café numbers...</div>; }
function initials(name = '') { return name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(); }
