import { useEffect, useState } from 'react';
import axios from 'axios';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
export default function Dashboard({ user }) {
  const [member, setMember] = useState(user); const [purchases, setPurchases] = useState([]); const [redemptions, setRedemptions] = useState([]); const [tab, setTab] = useState('purchases'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const id = user?.id || user?._id;
  useEffect(() => { const load = async () => { try { const config = { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }; const [memberResponse, purchasesResponse, redemptionsResponse] = await Promise.all([axios.get(`${API_URL}/api/members/${id}`, config), axios.get(`${API_URL}/api/purchases/history/${id}?limit=5`, config), axios.get(`${API_URL}/api/redemptions/history/${id}?limit=5`, config)]); setMember(memberResponse.data); setPurchases(purchasesResponse.data.purchases || []); setRedemptions(redemptionsResponse.data.redemptions || []); } catch (requestError) { setError(requestError.response?.data?.error || 'Could not load your rewards.'); } finally { setLoading(false); } }; if (id) load(); }, [id]);
  if (loading) return <main className="page-shell"><div className="loading-state"><span className="spinner" /> Brewing your rewards dashboard...</div></main>;
  return <main className="page-shell dashboard-page"><div className="dashboard-welcome"><div><p className="eyebrow">YOUR DAILY PERKS</p><h1>Welcome back, {member?.name?.split(' ')[0] || 'friend'} <span>✦</span></h1><p>Your next little reward is closer than you think.</p></div><div className={`tier-orb ${String(member?.tier || 'Bronze').toLowerCase()}`}><span>{member?.tier === 'Platinum' ? '💎' : member?.tier === 'Gold' ? '🏆' : member?.tier === 'Silver' ? '🥈' : '🌰'}</span><small>{member?.tier || 'Bronze'}</small></div></div>{error && <div className="alert error-message">⚠️ {error}</div>}<section className="member-hero"><div><p className="eyebrow">AVAILABLE TO ENJOY</p><strong>{member?.pointsBalance?.toLocaleString() || 0}</strong><span>points</span><p>Keep collecting. Good things are brewing.</p></div><div className="hero-cup">☕</div></section><section className="dashboard-stats"><Stat label="Lifetime earned" value={member?.totalPointsEarned || 0} icon="📈" tone="green" /><Stat label="Your earn rate" value={`${member?.tier === 'Platinum' ? '1.8' : member?.tier === 'Gold' ? '1.5' : member?.tier === 'Silver' ? '1.2' : '1'}×`} icon="⚡" tone="orange" /><Stat label="Next milestone" value={member?.tier === 'Platinum' ? 'Top tier' : member?.tier === 'Silver' ? 'Gold' : member?.tier === 'Gold' ? 'Platinum' : 'Silver'} icon="🎯" tone="purple" /></section><section className="history-panel panel-card"><div className="history-tabs"><button className={tab === 'purchases' ? 'active' : ''} onClick={() => setTab('purchases')}>🛍️ Purchases <span>{purchases.length}</span></button><button className={tab === 'redemptions' ? 'active' : ''} onClick={() => setTab('redemptions')}>🎁 Redemptions <span>{redemptions.length}</span></button></div>{tab === 'purchases' ? <HistoryRows items={purchases} empty="Your first purchase is the beginning of something good." render={(purchase) => <><span className="history-icon">☕</span><span><strong>Purchase at the café</strong><small>{new Date(purchase.timestamp).toLocaleDateString()} · ₹{purchase.amount}</small></span><b className="earned">+{purchase.pointsAwarded} pts</b></>} /> : <HistoryRows items={redemptions} empty="No rewards redeemed yet. Keep earning!" render={(redemption) => <><span className="history-icon">🎁</span><span><strong>{redemption.itemName}</strong><small>{new Date(redemption.timestamp).toLocaleDateString()}</small></span><b className="spent">−{redemption.pointsRedeemed} pts</b></>} />}</section></main>;
}
function Stat({ label, value, icon, tone }) { return <article className={`mini-stat tone-${tone}`}><span>{icon}</span><small>{label}</small><strong>{typeof value === 'number' ? value.toLocaleString() : value}</strong></article>; }
function HistoryRows({ items, empty, render }) { return items.length ? <div className="history-list dashboard-history">{items.map((item) => <div className="history-item" key={item._id}>{render(item)}</div>)}</div> : <div className="history-empty"><span>🌱</span><p>{empty}</p></div>; }
