import { useState } from 'react';
import axios from 'axios';
import { Link, useNavigate } from 'react-router-dom';

export default function LoginPage({ onLogin }) {
  const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const response = await axios.post(`${import.meta.env.VITE_API_URL || 'http://localhost:5000'}/api/auth/login`, form); onLogin(response.data.token, response.data.member); navigate('/dashboard'); } catch (requestError) { setError(requestError.response?.data?.error || 'Login failed. Please try again.'); } finally { setLoading(false); } };
  return <main className="auth-page"><section className="auth-visual"><div className="auth-visual-content"><span className="auth-badge">☕ MEMBERS CLUB</span><h1>Good coffee.<br /><em>Good company.</em><br />Good perks.</h1><p>Every cup is a small ritual. Your rewards should feel the same.</p><div className="coffee-orbit"><span>✦</span><strong>Every visit<br />counts</strong></div></div><span className="auth-quote">“The best reward is a reason to come back.”</span></section><section className="auth-form-side"><div className="auth-form-wrap"><Link to="/" className="back-link">← Back home</Link><div className="auth-heading"><p className="eyebrow">WELCOME BACK</p><h2>Ready for your next perk?</h2><p>Sign in to see your points and member benefits.</p></div>{error && <div className="alert error-message">⚠️ {error}</div>}<form onSubmit={submit} className="premium-form"><Field label="Email address" name="email" type="email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} placeholder="you@example.com" /><Field label="Password" name="password" type="password" value={form.password} onChange={(value) => setForm({ ...form, password: value })} placeholder="Your secret blend" /><button className="gradient-button full-width" disabled={loading}>{loading ? <><span className="spinner small" /> Signing you in...</> : <>Sign in to rewards <span>↗</span></>}</button></form><p className="auth-switch">New around here? <Link to="/register">Create your account</Link></p></div></section></main>;
}
function Field({ label, name, type, value, onChange, placeholder }) { return <label className="premium-field"><span>{label}</span><input name={name} type={type} required value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>; }
