import { useEffect, useState } from 'react';
import axios from 'axios';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
const tierClass = { Bronze: 'tier-bronze', Silver: 'tier-silver', Gold: 'tier-gold', Platinum: 'tier-platinum' };

export default function ProfilePage({ user, onLogout }) {
  const [member, setMember] = useState(user); const [purchases, setPurchases] = useState([]); const [redemptions, setRedemptions] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const memberId = user?.id || user?._id;
  useEffect(() => { const load = async () => { try { const config = { headers: { Authorization: `Bearer ${localStorage.getItem('token')}` } }; const [memberResponse, purchaseResponse, redemptionResponse] = await Promise.all([axios.get(`${API_URL}/api/members/${memberId}`, config), axios.get(`${API_URL}/api/purchases/history/${memberId}?limit=5`, config), axios.get(`${API_URL}/api/redemptions/history/${memberId}?limit=5`, config)]); setMember(memberResponse.data); setPurchases(purchaseResponse.data.purchases || []); setRedemptions(redemptionResponse.data.redemptions || []); } catch (requestError) { setError(requestError.response?.data?.error || 'Could not load your profile'); } finally { setLoading(false); } }; if (memberId) load(); }, [memberId]);
  if (loading) return <main className="page-shell"><Loader /></main>;
  return <main className="page-shell profile-page"><div className="page-intro profile-intro"><div><p className="eyebrow">☕ YOUR MEMBERSHIP</p><h1>A little more you.</h1><p>Your coffee story, all in one place.</p></div><button className="outline-button" onClick={onLogout}>Sign out ↗</button></div>{error && <div className="alert error-message">⚠️ {error}</div>}<section className="profile-hero"><div className="profile-identity"><div className="profile-avatar">{initials(member?.name)}</div><div><p className="eyebrow">MEMBER SINCE {new Date(member?.createdAt || Date.now()).getFullYear()}</p><h2>{member?.name}</h2><p>{member?.email} · {member?.phoneNumber}</p></div></div><span className={`tier-badge large ${tierClass[member?.tier] || tierClass.Bronze}`}>{member?.tier === 'Platinum' ? '💎' : '🏅'} {member?.tier || 'Bronze'} member</span></section><section className="profile-stats"><ProfileStat label="Points balance" value={member?.pointsBalance || 0} icon="✨" tone="orange" /><ProfileStat label="Current tier" value={member?.tier || 'Bronze'} icon="🏆" tone="yellow" /><ProfileStat label="Total earned" value={member?.totalPointsEarned || 0} icon="📈" tone="purple" /></section><div className="history-grid"><HistoryCard title="Recent purchases" icon="🛍️" items={purchases} empty="Your first reward is waiting." render={(purchase) => <><span><strong>₹{purchase.amount}</strong><small>{new Date(purchase.timestamp).toLocaleDateString()}</small></span><b>+{purchase.pointsAwarded} pts</b></>} /><HistoryCard title="Recent redemptions" icon="🎁" items={redemptions} empty="Nothing redeemed yet — keep earning!" render={(redemption) => <><span><strong>{redemption.itemName}</strong><small>{new Date(redemption.timestamp).toLocaleDateString()}</small></span><b className="spent">−{redemption.pointsRedeemed} pts</b></>} /></div></main>;
}

function ProfileStat({ label, value, icon, tone }) { return <article className={`profile-stat tone-${tone}`}><span>{icon}</span><small>{label}</small><strong>{typeof value === 'number' ? value.toLocaleString() : value}</strong></article>; }
function HistoryCard({ title, icon, items, empty, render }) { return <section className="panel-card history-card"><div className="panel-heading"><h2>{icon} {title}</h2><span className="history-count">{items.length} latest</span></div>{items.length ? <div className="history-list">{items.map((item) => <div className="history-item" key={item._id}>{render(item)}</div>)}</div> : <div className="history-empty"><span>☕</span><p>{empty}</p></div>}</section>; }
function Loader() { return <div className="loading-state"><span className="spinner" /> Preparing your profile...</div>; }
function initials(name = '') { return name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(); }
