import { useState } from 'react';
import axios from 'axios';
import { Link, useNavigate } from 'react-router-dom';

export default function RegisterPage({ onLogin }) {
  const [form, setForm] = useState({ name: '', email: '', phoneNumber: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setError(''); if (form.password !== form.confirmPassword) { setError('Your passwords do not match.'); return; } setLoading(true); try { const response = await axios.post(`${import.meta.env.VITE_API_URL || 'http://localhost:5000'}/api/auth/register`, { name: form.name, email: form.email, phoneNumber: form.phoneNumber, password: form.password }); onLogin(response.data.token, response.data.member); navigate('/dashboard'); } catch (requestError) { setError(requestError.response?.data?.error || 'Registration failed. Please try again.'); } finally { setLoading(false); } };
  return <main className="auth-page register-page"><section className="auth-visual"><div className="auth-visual-content"><span className="auth-badge">✦ JOIN THE CLUB</span><h1>Your table<br /><em>is waiting.</em></h1><p>Unlock thoughtful rewards, little surprises, and more reasons to make the café your happy place.</p><div className="benefit-stack"><span>🎁 Rewards from your first visit</span><span>📈 Levels that grow with you</span><span>💛 Made for regulars</span></div></div><span className="auth-quote">“A little loyalty goes a long way.”</span></section><section className="auth-form-side"><div className="auth-form-wrap"><Link to="/" className="back-link">← Back home</Link><div className="auth-heading"><p className="eyebrow">CREATE YOUR MEMBERSHIP</p><h2>Make yourself at home.</h2><p>Join the club and start earning on every purchase.</p></div>{error && <div className="alert error-message">⚠️ {error}</div>}<form onSubmit={submit} className="premium-form"><Field label="Full name" name="name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} placeholder="Your name" /><Field label="Email address" name="email" type="email" value={form.email} onChange={(value) => setForm({ ...form, email: value })} placeholder="you@example.com" /><Field label="Phone number" name="phoneNumber" type="tel" value={form.phoneNumber} onChange={(value) => setForm({ ...form, phoneNumber: value })} placeholder="9876543210" /><div className="form-two"><Field label="Password" name="password" type="password" value={form.password} onChange={(value) => setForm({ ...form, password: value })} placeholder="6+ characters" /><Field label="Confirm" name="confirmPassword" type="password" value={form.confirmPassword} onChange={(value) => setForm({ ...form, confirmPassword: value })} placeholder="Repeat it" /></div><button className="gradient-button full-width" disabled={loading}>{loading ? <><span className="spinner small" /> Creating your club card...</> : <>Start earning <span>↗</span></>}</button></form><p className="auth-switch">Already a member? <Link to="/login">Sign in here</Link></p></div></section></main>;
}
function Field({ label, name, type = 'text', value, onChange, placeholder }) { return <label className="premium-field"><span>{label}</span><input name={name} type={type} required value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} minLength={name.includes('password') ? 6 : undefined} /></label>; }
